export default {
    all: 'All',
    Incomplete: 'Incomplete',
    Complete: 'Complete',
    Late: 'Late',
    Not_Needed: 'Not Needed',
    Not_yet_started: 'Not Yet Started',
    Started: 'Started',
    Automatic: 'Automatic',
    Student: 'Student',
    FilterBy: 'Filter By',
    Legend: 'Legend',
    Course: 'Course',
    Section: 'Section',
    Semester: 'Semester',
    Status: 'Status',
    Task: 'Task',
    Workflows: 'Workflows',
    Subworkflow: 'Subworkflow',
    WorkflowID: 'WorkflowID',
    Options: 'Options',
    TaskActions: 'Task Actions',
    ReassignHistory: 'Reassign History',
    TaskProperties: 'Task Properties',
    TaskType: 'Task Type',
    AssignedTo: 'Assigned to',
    ViewDetail: 'View task in greater detail',
    ReopenTask: 'Re-open task for user',
    Reassign: 'Reassign this task to another user',
    Close: 'Close'
};
