let strings = {
    CreateProblemTitle: 'Create the Problem',
    EditProblemTitle: 'Edit the Problem',
    CommentTitle: 'Comment on This Problem',
    SolveProblemTitle: 'Solve the Problem',
    GradeProblemTitle: 'Grade the Solution',
    CritiqueTitle: 'Critique the Solution',
    ConsolidateProblemTitle: 'Consolidate the Grades',
    DisputeGradeTitle: 'Dispute Your Grade',
    ResolveDisputeTitle: 'Resolve the Dispute',
    Task: 'Task',
    Comments: 'Comments',
    ShowTaskRubric: 'Show Task Rubric',
    HideTaskRubric: 'Hide Task Rubric',
    InputErrorMessage: 'Sorry, there was an error sending your response. Please try again.',
    SaveSuccessMessage: 'Your work has been saved and will be loaded when you return',
    SubmitSuccessMessage: 'Task successfully submitted!',
    Submit: 'Submit',
    SaveForLater: 'Save for Later',
    WillDispute: 'Will Dispute',
    WillNotDispute: 'Will Not Dispute',
    TaskRubric: 'Task Rubric',
    TaskInstructions: 'Task Instructions',
    Grade: 'Grade',
    HideRubric: 'Hide Rubric',
    ShowRubric: 'Show Rubric',
    Rubric: 'Rubric',
    Instructions: 'Instructions',
    InputPlaceholder: 'Type your problem here',
    JustificationPlaceholder: 'Type your response here',
    Pass: 'Pass',
    Fail: 'Fail',
    LabelDirections: 'Choose from one of the labels below',
    Course: 'Course',
    Min: 'Min',
    NotAllowed: 'Sorry, you are not allowed to see this task',
    buttonLabel: 'Upload',
    filesLabel: 'Files',
    selectLabel: 'Select Files',
    uploadedLabel: 'Uploaded',
    Max: 'Max',

};

export default strings;
