export default {
    titleAddNewInstructor: 'Add New Instructor',
    titlePromoteInstructor: 'Promote Instructor',
    labelInstructorEmailAddress: 'Instructor Email Address',
    submit: 'Submit',
    status: 'Promoted',
    enhanced: 'Enhanced',
    email: 'Email',
    admin:'Admin',
    participant:"Participant",
    guest:'Guest',
    unknown:'Unkown',
    fn:'First Name',
    ln:'Last Name',
    organization:'Organization',
    sysRole:'System Role',
    testUser:'Test User',
    blocked:'Blocked',
    lastLogin:'Last Login',
    timeout:'Timeout',
    resetPW:'Reset Password',
    removeUser:'Remove Users',
    noUsers:'No Users',
    instructorAddedSuccess: 'Instructor added successfully!',
    instructorAddedFailure: 'Error: Email address was NOT updated! Please check your entered values.',
    instructorPromotedSuccess: 'Instructor promoted successfully!',
    instructorPromotedFailure: 'Error: Unable to promote instructor.',
    unblockedSuccess: ' was unblocked successfully',
    blockedSuccess:' was blocked successfully',
    unblockedFailure:' was unable to be unblocked',
    blockedFailure:' was unable to be blocked',
    pwResetSuccess:': password was reset successfully',
    pwResetFailure:': password was unable to be reset',
    removeSuccess:' was removed successfully',
    removeFailure:' is unable to be removed'
};