export default {
    GeneralSettings: 'General Settings',
    AverageNumOfAssignments: 'Average number of assignments',
    CourseGamificationFeatures: 'Course Gamification Features',
    PointsAwardedForEachTask: 'Points awarded for each task',
    AdvancedOptions: 'Advanced Options',
    Leaderboard: 'Leaderboard',
    UseAnnonymousNames: 'Use annonymous names',
    CompeteAgainstOtherCourses: 'Compete against other courses',
    NumberOfRanksToShow: 'Number of ranks to show',
    Save: 'Save',
    Levels: 'Levels',
    LevelThresholds: 'Level Thresholds',
    PointsAllocation: 'Points allocation',
    Goals: 'Goals',
    Requirements: 'Requirements',
    On: 'On',
    Off: 'Off',
    Low: 'Low',
    Medium: 'Medium',
    High: 'High',    
    Bronze: 'Bronze',
    Silver: 'Silver',
    Gold: 'Gold',
};