export default {
    AssignmentGrades: 'Assignment Grades',
    Assignment: 'Assignment',
    StudentInformation: 'Student Information',
    RegularTasks: 'Regular Tasks',
    ExtraCreditTasks: 'Extra Credit Tasks',
    Email: 'Email',
    LastName: 'Last Name',
    FirstName: 'First Name',
    Total: 'Total',
    CompletenessGrade: 'Completeness Grade',
    Grade: 'Current Grade',
    QualityGrade: 'Quality Grade',
    FinalGrade: 'Final Grade',
    Comments: 'Comments',
    ECCompletenessGrade: 'Extra Credit Completeness Grade',
    ECQualtiyGrade: 'Extra Credit Qualtiy Grade',
    ECGrade: 'Extra Credit Grade',
    ECComments: 'Extra Credit Comments',
    InstructorReport: 'Instructor Report',
    Student: 'Student',
    Task: 'Task',
    CombinedWeight: 'Combined Weight',
    WeightedGrade: 'Weighted Grade',
    UserName: 'UserName',
    LastName: "Last Name",
    FirstName:"First Name",
    AssignmentGrade:"Current Assignment Grade",
    CurrXCreditGrade:"Current Extra Credit Grade",
    NumXCreditTasks:"# Extra Credit Tasks",
    AssignmentGradeNoData:"No grades available for this assignment",
    AGRHeader:"Assignment Grades Report",
    PGRHeader:"Problem Grades Report",

    Problem:"Problem",
    ProblemGrade:'Current Problem Grade',
    ProblemsPerStudent: 'Original # Problems Per Student',
    WeightWithinAssignment: 'Weight Within Assignment',
    ScaledGrade: 'Current Scaled Grade Within Assignment',
    ScaledGradeProblem: "Current Scaled Grade Within Problem",

    ConvertedNumericValue: "Converted Numeric Value",
    

    WeightWithinProblem:'Weight Within Problem',
    ProblemGradeNoData: 'There are no grades for this problem',
    PTTGRHeader:'Problem Task and Timeliness Report',
    TimelinessGrade:'Timeliness Grade',
    TimelinessMaximumGrade: 'Timeliness Maximum Grade',

    Field:'Field',
    Type:'Type',
    Value:'Value',
    Max:'Max',
    WeightWTask:'Weight Within Task',
    ScaledGradeTask:'Scaled Grade Within Task',
    TaskGradeNoData:'There are no grades for this task',
    TGFRHeader: 'Task Grades Field Report',
    
    PTGDRGHeader: 'Problem Timeliness Grade Details Report',
    Status: 'Status',
    DaysLate: 'Days Late',
    PenaltyPerDay: 'Penalty Per Day',
    TotalPenalty: 'Total Penalty',
    



};